### ISSUE TITLE
"TiDB not support foreign key" clarification

### ISSUE THREAD

**Issue by pirate** [blacktear23/django_tidb#1]
Is there really no FK support at all? How are we supposed to build relational models?
Isn't that most of what using a relational database is for?

**Comment by blacktear23** [comment]
Yes, TiDB currently not support ForeignKey. You should manage relationship by yourself.

**Comment by pirate** [comment]
Interesting, I'll definitely wait until they add FK support as it's a critical feature for me.  Thanks for answering!
